/**
 * Build-time CMS snapshot loader for admin-tools dashboards.
 *
 * The dashboards are server-rendered with `force-dynamic` (cookies),
 * which puts them on the runtime function. Cloudflare Workers don't
 * ship the `content/` filesystem tree, so we cannot call
 * `getAllPages()` from `lib/cms.ts` (which uses fs.readdirSync) at
 * request time.
 *
 * Instead we read a JSON generated by `scripts/build-seo-snapshot.mjs`
 * which runs in `prebuild` (and is committed to the bundle by Next).
 * If the file is missing, prebuild creates an empty one so this
 * static ESM import always resolves.
 */
import snapshot from './_seo-snapshot.generated.json'
import type { CMSPage, CMSProduct, CMSStory } from './seo-types'

const typed = snapshot as { generatedAt: string; pages: CMSPage[]; products: CMSProduct[]; stories?: CMSStory[] }

export function getSnapshotPages(): CMSPage[] {
  return typed.pages || []
}

export function getSnapshotProducts(): CMSProduct[] {
  return typed.products || []
}

export function getSnapshotStories(): CMSStory[] {
  return typed.stories || []
}

export function getSnapshotMeta() {
  return { generatedAt: typed.generatedAt }
}
